name: mwc-env
channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - scipy
  - pandas
  - nibabel
  - networkx
  - scikit-learn
  - statsmodels
  - matplotlib
  - ipykernel
  - nilearn
  - seaborn
  - notebook
  - jupyterlab
  - pip
  - pip:
      - plotly
      - brainsmash
      - enigmatoolbox
